name: cogent-js

on:
  push:
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com/
          scope: '@interiordefine'
      - run: npm install
      - run: npm build
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
